# Generated by Django 4.1.3 on 2022-11-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.IntegerField(choices=[(1, 'HouseHold'), (2, 'Retailer')]),
        ),
    ]
