# Generated by Django 4.1.3 on 2022-11-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.IntegerField(choices=[(1, 'HouseHold'), (2, 'Small Scale Industry')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('HouseHold', 'HouseHold'), ('Small Scale Industry', 'Small Scale Industry')], max_length=50),
        ),
    ]
