# Generated by Django 4.1.3 on 2022-11-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subtext', models.CharField(blank=True, max_length=200, null=True)),
                ('aboutus', models.CharField(max_length=3000)),
                ('fb_link', models.CharField(blank=True, max_length=200, null=True)),
                ('ig_link', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=12, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'about us',
                'verbose_name_plural': 'about us',
            },
        ),
    ]
