# Generated by Django 4.1.3 on 2022-11-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('orders', '0005_order_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.stores'),
        ),
    ]
